name: flutter_lints_module
description: "flutter_lints JuneFlow Module"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/flutter_lints_module

version: 0.0.1+2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true